/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.convenio.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioPageDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.api.IConvenioPersistence;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.entity.ConvenioEntity;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.converter.ConvenioConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ConvenioPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ConvenioPersistence.class.getPackage())
				.addPackage(ConvenioEntity.class.getPackage())
				.addPackage(IConvenioPersistence.class.getPackage())
                .addPackage(ConvenioDTO.class.getPackage())
                .addPackage(ConvenioConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IConvenioPersistence convenioPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ConvenioEntity").executeUpdate();
	}

	private List<ConvenioEntity> data=new ArrayList<ConvenioEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ConvenioEntity entity=new ConvenioEntity();
			entity.setName(generateRandom(String.class));
			entity.setPaisId(generateRandom(Long.class));
			entity.setFacultaduniandesId(generateRandom(Long.class));
			entity.setDepartamentouniandesId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createConvenioTest(){
		ConvenioDTO dto=new ConvenioDTO();
		dto.setName(generateRandom(String.class));
		dto.setPaisId(generateRandom(Long.class));
		dto.setFacultaduniandesId(generateRandom(Long.class));
		dto.setDepartamentouniandesId(generateRandom(Long.class));
		
		ConvenioDTO result=convenioPersistence.createConvenio(dto);
		
		Assert.assertNotNull(result);
		
		ConvenioEntity entity=em.find(ConvenioEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getPaisId(), entity.getPaisId());
		Assert.assertEquals(dto.getFacultaduniandesId(), entity.getFacultaduniandesId());
		Assert.assertEquals(dto.getDepartamentouniandesId(), entity.getDepartamentouniandesId());
	}
	
	@Test
	public void getConveniosTest(){
		List<ConvenioDTO> list=convenioPersistence.getConvenios();
		Assert.assertEquals(list.size(), data.size());
        for(ConvenioDTO dto:list){
        	boolean found=false;
            for(ConvenioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getConvenioTest(){
		ConvenioEntity entity=data.get(0);
		ConvenioDTO dto=convenioPersistence.getConvenio(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getPaisId(), dto.getPaisId());
		Assert.assertEquals(entity.getFacultaduniandesId(), dto.getFacultaduniandesId());
		Assert.assertEquals(entity.getDepartamentouniandesId(), dto.getDepartamentouniandesId());
        
	}
	
	@Test
	public void deleteConvenioTest(){
		ConvenioEntity entity=data.get(0);
		convenioPersistence.deleteConvenio(entity.getId());
        ConvenioEntity deleted=em.find(ConvenioEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateConvenioTest(){
		ConvenioEntity entity=data.get(0);
		
		ConvenioDTO dto=new ConvenioDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setPaisId(generateRandom(Long.class));
		dto.setFacultaduniandesId(generateRandom(Long.class));
		dto.setDepartamentouniandesId(generateRandom(Long.class));
		
		
		convenioPersistence.updateConvenio(dto);
		
		
		ConvenioEntity resp=em.find(ConvenioEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getPaisId(), resp.getPaisId());	
		Assert.assertEquals(dto.getFacultaduniandesId(), resp.getFacultaduniandesId());	
		Assert.assertEquals(dto.getDepartamentouniandesId(), resp.getDepartamentouniandesId());	
	}
	
	@Test
	public void getConvenioPaginationTest(){
		//Page 1
		ConvenioPageDTO dto1=convenioPersistence.getConvenios(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ConvenioPageDTO dto2=convenioPersistence.getConvenios(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ConvenioDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ConvenioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ConvenioDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ConvenioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}