/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.experiencia.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.RoyalSystem.experiencia.logic.dto.ExperienciaDTO;
import co.edu.uniandes.csw.RoyalSystem.experiencia.logic.dto.ExperienciaPageDTO;
import co.edu.uniandes.csw.RoyalSystem.experiencia.logic.api._IExperienciaLogicService;
import co.edu.uniandes.csw.RoyalSystem.experiencia.persistence.api.IExperienciaPersistence;

public abstract class _ExperienciaLogicService implements _IExperienciaLogicService {

	@Inject
	protected IExperienciaPersistence persistance;

	public ExperienciaDTO createExperiencia(ExperienciaDTO experiencia){
		return persistance.createExperiencia( experiencia); 
    }

	public List<ExperienciaDTO> getExperiencias(){
		return persistance.getExperiencias(); 
	}

	public ExperienciaPageDTO getExperiencias(Integer page, Integer maxRecords){
		return persistance.getExperiencias(page, maxRecords); 
	}

	public ExperienciaDTO getExperiencia(Long id){
		return persistance.getExperiencia(id); 
	}

	public void deleteExperiencia(Long id){
	    persistance.deleteExperiencia(id); 
	}

	public void updateExperiencia(ExperienciaDTO experiencia){
	    persistance.updateExperiencia(experiencia); 
	}	
}