/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.cliente.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.RoyalSystem.cliente.logic.dto.ClienteDTO;
import co.edu.uniandes.csw.RoyalSystem.cliente.logic.dto.ClientePageDTO;
import co.edu.uniandes.csw.RoyalSystem.cliente.logic.api._IClienteLogicService;
import co.edu.uniandes.csw.RoyalSystem.cliente.persistence.api.IClientePersistence;

public abstract class _ClienteLogicService implements _IClienteLogicService {

	@Inject
	protected IClientePersistence persistance;

	public ClienteDTO createCliente(ClienteDTO cliente){
		return persistance.createCliente( cliente); 
    }

	public List<ClienteDTO> getClientes(){
		return persistance.getClientes(); 
	}

	public ClientePageDTO getClientes(Integer page, Integer maxRecords){
		return persistance.getClientes(page, maxRecords); 
	}

	public ClienteDTO getCliente(Long id){
		return persistance.getCliente(id); 
	}

	public void deleteCliente(Long id){
	    persistance.deleteCliente(id); 
	}

	public void updateCliente(ClienteDTO cliente){
	    persistance.updateCliente(cliente); 
	}	
}