/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.intercambio.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.intercambio.logic.dto.IntercambioDTO;
import co.edu.uniandes.csw.RoyalSystem.intercambio.logic.dto.IntercambioPageDTO;
import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.api._IIntercambioPersistence;
import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.converter.IntercambioConverter;
import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.entity.IntercambioEntity;

public abstract class _IntercambioPersistence implements _IIntercambioPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public IntercambioDTO createIntercambio(IntercambioDTO intercambio) {
		IntercambioEntity entity=IntercambioConverter.persistenceDTO2Entity(intercambio);
		entityManager.persist(entity);
		return IntercambioConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<IntercambioDTO> getIntercambios() {
		Query q = entityManager.createQuery("select u from IntercambioEntity u");
		return IntercambioConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public IntercambioPageDTO getIntercambios(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from IntercambioEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from IntercambioEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		IntercambioPageDTO response = new IntercambioPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(IntercambioConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public IntercambioDTO getIntercambio(Long id) {
		return IntercambioConverter.entity2PersistenceDTO(entityManager.find(IntercambioEntity.class, id));
	}

	public void deleteIntercambio(Long id) {
		IntercambioEntity entity=entityManager.find(IntercambioEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateIntercambio(IntercambioDTO detail) {
		IntercambioEntity entity=entityManager.merge(IntercambioConverter.persistenceDTO2Entity(detail));
		IntercambioConverter.entity2PersistenceDTO(entity);
	}

}