/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.departamentouniandes.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.departamentouniandes.logic.dto.DepartamentoUniandesPageDTO;
import co.edu.uniandes.csw.RoyalSystem.departamentouniandes.logic.dto.DepartamentoUniandesDTO;
import co.edu.uniandes.csw.RoyalSystem.departamentouniandes.persistence.api.IDepartamentoUniandesPersistence;
import co.edu.uniandes.csw.RoyalSystem.departamentouniandes.persistence.entity.DepartamentoUniandesEntity;
import co.edu.uniandes.csw.RoyalSystem.departamentouniandes.persistence.converter.DepartamentoUniandesConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class DepartamentoUniandesPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(DepartamentoUniandesPersistence.class.getPackage())
				.addPackage(DepartamentoUniandesEntity.class.getPackage())
				.addPackage(IDepartamentoUniandesPersistence.class.getPackage())
                .addPackage(DepartamentoUniandesDTO.class.getPackage())
                .addPackage(DepartamentoUniandesConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IDepartamentoUniandesPersistence departamentoUniandesPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from DepartamentoUniandesEntity").executeUpdate();
	}

	private List<DepartamentoUniandesEntity> data=new ArrayList<DepartamentoUniandesEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			DepartamentoUniandesEntity entity=new DepartamentoUniandesEntity();
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createDepartamentoUniandesTest(){
		DepartamentoUniandesDTO dto=new DepartamentoUniandesDTO();
		dto.setName(generateRandom(String.class));
		
		DepartamentoUniandesDTO result=departamentoUniandesPersistence.createDepartamentoUniandes(dto);
		
		Assert.assertNotNull(result);
		
		DepartamentoUniandesEntity entity=em.find(DepartamentoUniandesEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getDepartamentoUniandessTest(){
		List<DepartamentoUniandesDTO> list=departamentoUniandesPersistence.getDepartamentoUniandess();
		Assert.assertEquals(list.size(), data.size());
        for(DepartamentoUniandesDTO dto:list){
        	boolean found=false;
            for(DepartamentoUniandesEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getDepartamentoUniandesTest(){
		DepartamentoUniandesEntity entity=data.get(0);
		DepartamentoUniandesDTO dto=departamentoUniandesPersistence.getDepartamentoUniandes(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteDepartamentoUniandesTest(){
		DepartamentoUniandesEntity entity=data.get(0);
		departamentoUniandesPersistence.deleteDepartamentoUniandes(entity.getId());
        DepartamentoUniandesEntity deleted=em.find(DepartamentoUniandesEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateDepartamentoUniandesTest(){
		DepartamentoUniandesEntity entity=data.get(0);
		
		DepartamentoUniandesDTO dto=new DepartamentoUniandesDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		
		
		departamentoUniandesPersistence.updateDepartamentoUniandes(dto);
		
		
		DepartamentoUniandesEntity resp=em.find(DepartamentoUniandesEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
	
	@Test
	public void getDepartamentoUniandesPaginationTest(){
		//Page 1
		DepartamentoUniandesPageDTO dto1=departamentoUniandesPersistence.getDepartamentoUniandess(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        DepartamentoUniandesPageDTO dto2=departamentoUniandesPersistence.getDepartamentoUniandess(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(DepartamentoUniandesDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(DepartamentoUniandesEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(DepartamentoUniandesDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(DepartamentoUniandesEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}