/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.facultaduniandes.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.logic.dto.FacultadUniandesDTO;
import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.logic.dto.FacultadUniandesPageDTO;
import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.persistence.api._IFacultadUniandesPersistence;
import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.persistence.converter.FacultadUniandesConverter;
import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.persistence.entity.FacultadUniandesEntity;

public abstract class _FacultadUniandesPersistence implements _IFacultadUniandesPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public FacultadUniandesDTO createFacultadUniandes(FacultadUniandesDTO facultadUniandes) {
		FacultadUniandesEntity entity=FacultadUniandesConverter.persistenceDTO2Entity(facultadUniandes);
		entityManager.persist(entity);
		return FacultadUniandesConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<FacultadUniandesDTO> getFacultadUniandess() {
		Query q = entityManager.createQuery("select u from FacultadUniandesEntity u");
		return FacultadUniandesConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public FacultadUniandesPageDTO getFacultadUniandess(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from FacultadUniandesEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from FacultadUniandesEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		FacultadUniandesPageDTO response = new FacultadUniandesPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(FacultadUniandesConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public FacultadUniandesDTO getFacultadUniandes(Long id) {
		return FacultadUniandesConverter.entity2PersistenceDTO(entityManager.find(FacultadUniandesEntity.class, id));
	}

	public void deleteFacultadUniandes(Long id) {
		FacultadUniandesEntity entity=entityManager.find(FacultadUniandesEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateFacultadUniandes(FacultadUniandesDTO detail) {
		FacultadUniandesEntity entity=entityManager.merge(FacultadUniandesConverter.persistenceDTO2Entity(detail));
		FacultadUniandesConverter.entity2PersistenceDTO(entity);
	}

}