/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraPageDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.api.IEntidadExtranjeraLogicService;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.EntidadExtranjeraPersistence;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.api.IEntidadExtranjeraPersistence;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.entity.EntidadExtranjeraEntity;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.converter.EntidadExtranjeraConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EntidadExtranjeraLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EntidadExtranjeraLogicService.class.getPackage())
				.addPackage(IEntidadExtranjeraLogicService.class.getPackage())
				.addPackage(EntidadExtranjeraPersistence.class.getPackage())
				.addPackage(EntidadExtranjeraEntity.class.getPackage())
				.addPackage(IEntidadExtranjeraPersistence.class.getPackage())
                .addPackage(EntidadExtranjeraDTO.class.getPackage())
                .addPackage(EntidadExtranjeraConverter.class.getPackage())
                .addPackage(EntidadExtranjeraEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEntidadExtranjeraLogicService entidadExtranjeraLogicService;
	
	@Inject
	private IEntidadExtranjeraPersistence entidadExtranjeraPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<EntidadExtranjeraDTO> dtos=entidadExtranjeraPersistence.getEntidadExtranjeras();
		for(EntidadExtranjeraDTO dto:dtos){
			entidadExtranjeraPersistence.deleteEntidadExtranjera(dto.getId());
		}
	}

	private List<EntidadExtranjeraDTO> data=new ArrayList<EntidadExtranjeraDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EntidadExtranjeraDTO pdto=new EntidadExtranjeraDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setLink(generateRandom(String.class));
			pdto=entidadExtranjeraPersistence.createEntidadExtranjera(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createEntidadExtranjeraTest(){
		EntidadExtranjeraDTO ldto=new EntidadExtranjeraDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setLink(generateRandom(String.class));
		
		
		EntidadExtranjeraDTO result=entidadExtranjeraLogicService.createEntidadExtranjera(ldto);
		
		Assert.assertNotNull(result);
		
		EntidadExtranjeraDTO pdto=entidadExtranjeraPersistence.getEntidadExtranjera(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getLink(), pdto.getLink());	
	}
	
	@Test
	public void getEntidadExtranjerasTest(){
		List<EntidadExtranjeraDTO> list=entidadExtranjeraLogicService.getEntidadExtranjeras();
		Assert.assertEquals(list.size(), data.size());
        for(EntidadExtranjeraDTO ldto:list){
        	boolean found=false;
            for(EntidadExtranjeraDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEntidadExtranjeraTest(){
		EntidadExtranjeraDTO pdto=data.get(0);
		EntidadExtranjeraDTO ldto=entidadExtranjeraLogicService.getEntidadExtranjera(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getLink(), ldto.getLink());
        
	}
	
	@Test
	public void deleteEntidadExtranjeraTest(){
		EntidadExtranjeraDTO pdto=data.get(0);
		entidadExtranjeraLogicService.deleteEntidadExtranjera(pdto.getId());
        EntidadExtranjeraDTO deleted=entidadExtranjeraPersistence.getEntidadExtranjera(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEntidadExtranjeraTest(){
		EntidadExtranjeraDTO pdto=data.get(0);
		
		EntidadExtranjeraDTO ldto=new EntidadExtranjeraDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setLink(generateRandom(String.class));
		
		
		entidadExtranjeraLogicService.updateEntidadExtranjera(ldto);
		
		
		EntidadExtranjeraDTO resp=entidadExtranjeraPersistence.getEntidadExtranjera(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getLink(), resp.getLink());	
	}
	
	@Test
	public void getEntidadExtranjeraPaginationTest(){
		
		EntidadExtranjeraPageDTO dto1=entidadExtranjeraLogicService.getEntidadExtranjeras(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		EntidadExtranjeraPageDTO dto2=entidadExtranjeraLogicService.getEntidadExtranjeras(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(EntidadExtranjeraDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(EntidadExtranjeraDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EntidadExtranjeraDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EntidadExtranjeraDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        EntidadExtranjeraPageDTO dto3=entidadExtranjeraLogicService.getEntidadExtranjeras(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(EntidadExtranjeraDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(EntidadExtranjeraDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}