/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.entity.EntidadExtranjeraEntity;

public abstract class _EntidadExtranjeraConverter {

	public static EntidadExtranjeraDTO entity2PersistenceDTO(EntidadExtranjeraEntity entity){
		if (entity != null) {
			EntidadExtranjeraDTO dto = new EntidadExtranjeraDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setLink(entity.getLink());
			return dto;
		}else{
			return null;
		}
	}
	
	public static EntidadExtranjeraEntity persistenceDTO2Entity(EntidadExtranjeraDTO dto){
		if(dto!=null){
			EntidadExtranjeraEntity entity=new EntidadExtranjeraEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setLink(dto.getLink());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<EntidadExtranjeraDTO> entity2PersistenceDTOList(List<EntidadExtranjeraEntity> entities){
		List<EntidadExtranjeraDTO> dtos=new ArrayList<EntidadExtranjeraDTO>();
		for(EntidadExtranjeraEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<EntidadExtranjeraEntity> persistenceDTO2EntityList(List<EntidadExtranjeraDTO> dtos){
		List<EntidadExtranjeraEntity> entities=new ArrayList<EntidadExtranjeraEntity>();
		for(EntidadExtranjeraDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}