/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraPageDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.api._IEntidadExtranjeraLogicService;

public abstract class _EntidadExtranjeraMockLogicService implements _IEntidadExtranjeraLogicService {

	private Long id= new Long(1);
	protected List<EntidadExtranjeraDTO> data=new ArrayList<EntidadExtranjeraDTO>();

	public EntidadExtranjeraDTO createEntidadExtranjera(EntidadExtranjeraDTO entidadExtranjera){
		id++;
		entidadExtranjera.setId(id);
		data.add(entidadExtranjera);
		return entidadExtranjera;
    }
    
    public List<EntidadExtranjeraDTO> getEntidadExtranjeras(){
		return data; 
	}

	public EntidadExtranjeraPageDTO getEntidadExtranjeras(Integer page, Integer maxRecords){
		EntidadExtranjeraPageDTO response = new EntidadExtranjeraPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public EntidadExtranjeraDTO getEntidadExtranjera(Long id){
		for(EntidadExtranjeraDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteEntidadExtranjera(Long id){
	    EntidadExtranjeraDTO delete=null;
		for(EntidadExtranjeraDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateEntidadExtranjera(EntidadExtranjeraDTO entidadExtranjera){
	    EntidadExtranjeraDTO delete=null;
		for(EntidadExtranjeraDTO data1:data){
			if(data1.getId().equals(entidadExtranjera.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(entidadExtranjera);
		} 
	}	
}