/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.estadohomologacion.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.logic.dto.EstadoHomologacionDTO;
import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.logic.dto.EstadoHomologacionPageDTO;
import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.persistence.api._IEstadoHomologacionPersistence;
import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.persistence.converter.EstadoHomologacionConverter;
import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.persistence.entity.EstadoHomologacionEntity;

public abstract class _EstadoHomologacionPersistence implements _IEstadoHomologacionPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public EstadoHomologacionDTO createEstadoHomologacion(EstadoHomologacionDTO estadoHomologacion) {
		EstadoHomologacionEntity entity=EstadoHomologacionConverter.persistenceDTO2Entity(estadoHomologacion);
		entityManager.persist(entity);
		return EstadoHomologacionConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<EstadoHomologacionDTO> getEstadoHomologacions() {
		Query q = entityManager.createQuery("select u from EstadoHomologacionEntity u");
		return EstadoHomologacionConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public EstadoHomologacionPageDTO getEstadoHomologacions(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from EstadoHomologacionEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from EstadoHomologacionEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		EstadoHomologacionPageDTO response = new EstadoHomologacionPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(EstadoHomologacionConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public EstadoHomologacionDTO getEstadoHomologacion(Long id) {
		return EstadoHomologacionConverter.entity2PersistenceDTO(entityManager.find(EstadoHomologacionEntity.class, id));
	}

	public void deleteEstadoHomologacion(Long id) {
		EstadoHomologacionEntity entity=entityManager.find(EstadoHomologacionEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateEstadoHomologacion(EstadoHomologacionDTO detail) {
		EstadoHomologacionEntity entity=entityManager.merge(EstadoHomologacionConverter.persistenceDTO2Entity(detail));
		EstadoHomologacionConverter.entity2PersistenceDTO(entity);
	}

}