/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.cliente.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.cliente.logic.dto.ClientePageDTO;
import co.edu.uniandes.csw.RoyalSystem.cliente.logic.dto.ClienteDTO;
import co.edu.uniandes.csw.RoyalSystem.cliente.persistence.api.IClientePersistence;
import co.edu.uniandes.csw.RoyalSystem.cliente.persistence.entity.ClienteEntity;
import co.edu.uniandes.csw.RoyalSystem.cliente.persistence.converter.ClienteConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ClientePersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ClientePersistence.class.getPackage())
				.addPackage(ClienteEntity.class.getPackage())
				.addPackage(IClientePersistence.class.getPackage())
                .addPackage(ClienteDTO.class.getPackage())
                .addPackage(ClienteConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IClientePersistence clientePersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ClienteEntity").executeUpdate();
	}

	private List<ClienteEntity> data=new ArrayList<ClienteEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ClienteEntity entity=new ClienteEntity();
			entity.setName(generateRandom(String.class));
			entity.setCodigo(generateRandom(Integer.class));
			entity.setCorreo(generateRandom(String.class));
			entity.setTipoId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createClienteTest(){
		ClienteDTO dto=new ClienteDTO();
		dto.setName(generateRandom(String.class));
		dto.setCodigo(generateRandom(Integer.class));
		dto.setCorreo(generateRandom(String.class));
		dto.setTipoId(generateRandom(Long.class));
		
		ClienteDTO result=clientePersistence.createCliente(dto);
		
		Assert.assertNotNull(result);
		
		ClienteEntity entity=em.find(ClienteEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getCodigo(), entity.getCodigo());
		Assert.assertEquals(dto.getCorreo(), entity.getCorreo());
		Assert.assertEquals(dto.getTipoId(), entity.getTipoId());
	}
	
	@Test
	public void getClientesTest(){
		List<ClienteDTO> list=clientePersistence.getClientes();
		Assert.assertEquals(list.size(), data.size());
        for(ClienteDTO dto:list){
        	boolean found=false;
            for(ClienteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getClienteTest(){
		ClienteEntity entity=data.get(0);
		ClienteDTO dto=clientePersistence.getCliente(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getCodigo(), dto.getCodigo());
		Assert.assertEquals(entity.getCorreo(), dto.getCorreo());
		Assert.assertEquals(entity.getTipoId(), dto.getTipoId());
        
	}
	
	@Test
	public void deleteClienteTest(){
		ClienteEntity entity=data.get(0);
		clientePersistence.deleteCliente(entity.getId());
        ClienteEntity deleted=em.find(ClienteEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateClienteTest(){
		ClienteEntity entity=data.get(0);
		
		ClienteDTO dto=new ClienteDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setCodigo(generateRandom(Integer.class));
		dto.setCorreo(generateRandom(String.class));
		dto.setTipoId(generateRandom(Long.class));
		
		
		clientePersistence.updateCliente(dto);
		
		
		ClienteEntity resp=em.find(ClienteEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getCodigo(), resp.getCodigo());	
		Assert.assertEquals(dto.getCorreo(), resp.getCorreo());	
		Assert.assertEquals(dto.getTipoId(), resp.getTipoId());	
	}
	
	@Test
	public void getClientePaginationTest(){
		//Page 1
		ClientePageDTO dto1=clientePersistence.getClientes(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ClientePageDTO dto2=clientePersistence.getClientes(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ClienteDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ClienteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ClienteDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ClienteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}