/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.facultaduniandes.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.logic.dto.FacultadUniandesDTO;
import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.logic.dto.FacultadUniandesPageDTO;
import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.logic.api._IFacultadUniandesLogicService;
import co.edu.uniandes.csw.RoyalSystem.facultaduniandes.persistence.api.IFacultadUniandesPersistence;

public abstract class _FacultadUniandesLogicService implements _IFacultadUniandesLogicService {

	@Inject
	protected IFacultadUniandesPersistence persistance;

	public FacultadUniandesDTO createFacultadUniandes(FacultadUniandesDTO facultadUniandes){
		return persistance.createFacultadUniandes( facultadUniandes); 
    }

	public List<FacultadUniandesDTO> getFacultadUniandess(){
		return persistance.getFacultadUniandess(); 
	}

	public FacultadUniandesPageDTO getFacultadUniandess(Integer page, Integer maxRecords){
		return persistance.getFacultadUniandess(page, maxRecords); 
	}

	public FacultadUniandesDTO getFacultadUniandes(Long id){
		return persistance.getFacultadUniandes(id); 
	}

	public void deleteFacultadUniandes(Long id){
	    persistance.deleteFacultadUniandes(id); 
	}

	public void updateFacultadUniandes(FacultadUniandesDTO facultadUniandes){
	    persistance.updateFacultadUniandes(facultadUniandes); 
	}	
}