/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.materiauniandes.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.materiauniandes.logic.dto.MateriaUniandesPageDTO;
import co.edu.uniandes.csw.RoyalSystem.materiauniandes.logic.dto.MateriaUniandesDTO;
import co.edu.uniandes.csw.RoyalSystem.materiauniandes.persistence.api.IMateriaUniandesPersistence;
import co.edu.uniandes.csw.RoyalSystem.materiauniandes.persistence.entity.MateriaUniandesEntity;
import co.edu.uniandes.csw.RoyalSystem.materiauniandes.persistence.converter.MateriaUniandesConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class MateriaUniandesPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(MateriaUniandesPersistence.class.getPackage())
				.addPackage(MateriaUniandesEntity.class.getPackage())
				.addPackage(IMateriaUniandesPersistence.class.getPackage())
                .addPackage(MateriaUniandesDTO.class.getPackage())
                .addPackage(MateriaUniandesConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IMateriaUniandesPersistence materiaUniandesPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from MateriaUniandesEntity").executeUpdate();
	}

	private List<MateriaUniandesEntity> data=new ArrayList<MateriaUniandesEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			MateriaUniandesEntity entity=new MateriaUniandesEntity();
			entity.setName(generateRandom(String.class));
			entity.setCodigo(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createMateriaUniandesTest(){
		MateriaUniandesDTO dto=new MateriaUniandesDTO();
		dto.setName(generateRandom(String.class));
		dto.setCodigo(generateRandom(String.class));
		
		MateriaUniandesDTO result=materiaUniandesPersistence.createMateriaUniandes(dto);
		
		Assert.assertNotNull(result);
		
		MateriaUniandesEntity entity=em.find(MateriaUniandesEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getCodigo(), entity.getCodigo());
	}
	
	@Test
	public void getMateriaUniandessTest(){
		List<MateriaUniandesDTO> list=materiaUniandesPersistence.getMateriaUniandess();
		Assert.assertEquals(list.size(), data.size());
        for(MateriaUniandesDTO dto:list){
        	boolean found=false;
            for(MateriaUniandesEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getMateriaUniandesTest(){
		MateriaUniandesEntity entity=data.get(0);
		MateriaUniandesDTO dto=materiaUniandesPersistence.getMateriaUniandes(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getCodigo(), dto.getCodigo());
        
	}
	
	@Test
	public void deleteMateriaUniandesTest(){
		MateriaUniandesEntity entity=data.get(0);
		materiaUniandesPersistence.deleteMateriaUniandes(entity.getId());
        MateriaUniandesEntity deleted=em.find(MateriaUniandesEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateMateriaUniandesTest(){
		MateriaUniandesEntity entity=data.get(0);
		
		MateriaUniandesDTO dto=new MateriaUniandesDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setCodigo(generateRandom(String.class));
		
		
		materiaUniandesPersistence.updateMateriaUniandes(dto);
		
		
		MateriaUniandesEntity resp=em.find(MateriaUniandesEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getCodigo(), resp.getCodigo());	
	}
	
	@Test
	public void getMateriaUniandesPaginationTest(){
		//Page 1
		MateriaUniandesPageDTO dto1=materiaUniandesPersistence.getMateriaUniandess(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        MateriaUniandesPageDTO dto2=materiaUniandesPersistence.getMateriaUniandess(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(MateriaUniandesDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(MateriaUniandesEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(MateriaUniandesDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(MateriaUniandesEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}