/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.intercambio.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.RoyalSystem.intercambio.logic.dto.IntercambioDTO;
import co.edu.uniandes.csw.RoyalSystem.intercambio.logic.dto.IntercambioPageDTO;
import co.edu.uniandes.csw.RoyalSystem.intercambio.logic.api._IIntercambioLogicService;
import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.api.IIntercambioPersistence;

public abstract class _IntercambioLogicService implements _IIntercambioLogicService {

	@Inject
	protected IIntercambioPersistence persistance;

	public IntercambioDTO createIntercambio(IntercambioDTO intercambio){
		return persistance.createIntercambio( intercambio); 
    }

	public List<IntercambioDTO> getIntercambios(){
		return persistance.getIntercambios(); 
	}

	public IntercambioPageDTO getIntercambios(Integer page, Integer maxRecords){
		return persistance.getIntercambios(page, maxRecords); 
	}

	public IntercambioDTO getIntercambio(Long id){
		return persistance.getIntercambio(id); 
	}

	public void deleteIntercambio(Long id){
	    persistance.deleteIntercambio(id); 
	}

	public void updateIntercambio(IntercambioDTO intercambio){
	    persistance.updateIntercambio(intercambio); 
	}	
}