/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.archivo.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.archivo.logic.dto.ArchivoPageDTO;
import co.edu.uniandes.csw.RoyalSystem.archivo.logic.dto.ArchivoDTO;
import co.edu.uniandes.csw.RoyalSystem.archivo.persistence.api.IArchivoPersistence;
import co.edu.uniandes.csw.RoyalSystem.archivo.persistence.entity.ArchivoEntity;
import co.edu.uniandes.csw.RoyalSystem.archivo.persistence.converter.ArchivoConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ArchivoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ArchivoPersistence.class.getPackage())
				.addPackage(ArchivoEntity.class.getPackage())
				.addPackage(IArchivoPersistence.class.getPackage())
                .addPackage(ArchivoDTO.class.getPackage())
                .addPackage(ArchivoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IArchivoPersistence archivoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ArchivoEntity").executeUpdate();
	}

	private List<ArchivoEntity> data=new ArrayList<ArchivoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ArchivoEntity entity=new ArchivoEntity();
			entity.setName(generateRandom(String.class));
			entity.setLink(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createArchivoTest(){
		ArchivoDTO dto=new ArchivoDTO();
		dto.setName(generateRandom(String.class));
		dto.setLink(generateRandom(String.class));
		
		ArchivoDTO result=archivoPersistence.createArchivo(dto);
		
		Assert.assertNotNull(result);
		
		ArchivoEntity entity=em.find(ArchivoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getLink(), entity.getLink());
	}
	
	@Test
	public void getArchivosTest(){
		List<ArchivoDTO> list=archivoPersistence.getArchivos();
		Assert.assertEquals(list.size(), data.size());
        for(ArchivoDTO dto:list){
        	boolean found=false;
            for(ArchivoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getArchivoTest(){
		ArchivoEntity entity=data.get(0);
		ArchivoDTO dto=archivoPersistence.getArchivo(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getLink(), dto.getLink());
        
	}
	
	@Test
	public void deleteArchivoTest(){
		ArchivoEntity entity=data.get(0);
		archivoPersistence.deleteArchivo(entity.getId());
        ArchivoEntity deleted=em.find(ArchivoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateArchivoTest(){
		ArchivoEntity entity=data.get(0);
		
		ArchivoDTO dto=new ArchivoDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setLink(generateRandom(String.class));
		
		
		archivoPersistence.updateArchivo(dto);
		
		
		ArchivoEntity resp=em.find(ArchivoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getLink(), resp.getLink());	
	}
	
	@Test
	public void getArchivoPaginationTest(){
		//Page 1
		ArchivoPageDTO dto1=archivoPersistence.getArchivos(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ArchivoPageDTO dto2=archivoPersistence.getArchivos(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ArchivoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ArchivoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ArchivoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ArchivoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}