/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.convenio.master.persistence;
import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.dto.HomologacionDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.master.persistence.entity.ConveniohomologacionEntity;
import co.edu.uniandes.csw.RoyalSystem.homologacion.persistence.converter.HomologacionConverter;
import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.master.logic.dto.ConvenioMasterDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.master.persistence.api._IConvenioMasterPersistence;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.api.IConvenioPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _ConvenioMasterPersistence implements _IConvenioMasterPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IConvenioPersistence convenioPersistence;  

    public ConvenioMasterDTO getConvenio(Long convenioId) {
        ConvenioMasterDTO convenioMasterDTO = new ConvenioMasterDTO();
        ConvenioDTO convenio = convenioPersistence.getConvenio(convenioId);
        convenioMasterDTO.setConvenioEntity(convenio);
        convenioMasterDTO.setListhomologacion(getConveniohomologacionEntityList(convenioId));
        return convenioMasterDTO;
    }

    public ConveniohomologacionEntity createConveniohomologacionEntity(ConveniohomologacionEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteConveniohomologacionEntity(Long convenioId, Long homologacionId) {
        Query q = entityManager.createNamedQuery("ConveniohomologacionEntity.deleteConveniohomologacionEntity");
        q.setParameter("convenioId", convenioId);
        q.setParameter("homologacionId", homologacionId);
        q.executeUpdate();
    }

    public List<HomologacionDTO> getConveniohomologacionEntityList(Long convenioId) {
        ArrayList<HomologacionDTO> resp = new ArrayList<HomologacionDTO>();
        Query q = entityManager.createNamedQuery("ConveniohomologacionEntity.getByMasterId");
        q.setParameter("convenioId",convenioId);
        List<ConveniohomologacionEntity> qResult =  q.getResultList();
        for (ConveniohomologacionEntity entity : qResult) { 
            if(entity.getHomologacionIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(HomologacionConverter.entity2PersistenceDTO(entity.getHomologacionIdEntity()));
        }
        return resp;
    }

}
