/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.experiencia.master.persistence.entity;

import co.edu.uniandes.csw.RoyalSystem.comentario.persistence.entity.ComentarioEntity;
import co.edu.uniandes.csw.RoyalSystem.experiencia.persistence.entity.ExperienciaEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ExperienciacomentarioEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ExperienciacomentarioEntity.getByMasterId", query = "SELECT  u FROM ExperienciacomentarioEntity u WHERE u.experienciaId=:experienciaId"),
    @NamedQuery(name = "ExperienciacomentarioEntity.deleteExperienciacomentarioEntity", query = "DELETE FROM ExperienciacomentarioEntity u WHERE u.experienciaId=:experienciaId and  u.comentarioId=:comentarioId")
})
public class ExperienciacomentarioEntity implements Serializable {

    @Id
    @Column(name = "experienciaId")
    private Long experienciaId;
    @Id
    @Column(name = "comentarioId")
    private Long comentarioId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "experienciaId", referencedColumnName = "id")
    @JoinFetch
    private ComentarioEntity experienciaIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "comentarioId", referencedColumnName = "id")
    @JoinFetch
    private ComentarioEntity comentarioIdEntity; 

    public ExperienciacomentarioEntity() {
    }

    public ExperienciacomentarioEntity(Long experienciaId, Long comentarioId) {
        this.experienciaId =experienciaId;
        this.comentarioId = comentarioId;
    }

    public Long getExperienciaId() {
        return experienciaId;
    }

    public void setExperienciaId(Long experienciaId) {
        this.experienciaId = experienciaId;
    }

    public Long getComentarioId() {
        return comentarioId;
    }

    public void setComentarioId(Long comentarioId) {
        this.comentarioId = comentarioId;
    }

    public ComentarioEntity getExperienciaIdEntity() {
        return experienciaIdEntity;
    }

    public void setExperienciaIdEntity(ComentarioEntity experienciaIdEntity) {
        this.experienciaIdEntity = experienciaIdEntity;
    }

    public ComentarioEntity getComentarioIdEntity() {
        return comentarioIdEntity;
    }

    public void setComentarioIdEntity(ComentarioEntity comentarioIdEntity) {
        this.comentarioIdEntity = comentarioIdEntity;
    }

}
