/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.comentario.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.comentario.logic.dto.ComentarioDTO;
import co.edu.uniandes.csw.RoyalSystem.comentario.logic.dto.ComentarioPageDTO;
import co.edu.uniandes.csw.RoyalSystem.comentario.persistence.api._IComentarioPersistence;
import co.edu.uniandes.csw.RoyalSystem.comentario.persistence.converter.ComentarioConverter;
import co.edu.uniandes.csw.RoyalSystem.comentario.persistence.entity.ComentarioEntity;

public abstract class _ComentarioPersistence implements _IComentarioPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public ComentarioDTO createComentario(ComentarioDTO comentario) {
		ComentarioEntity entity=ComentarioConverter.persistenceDTO2Entity(comentario);
		entityManager.persist(entity);
		return ComentarioConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ComentarioDTO> getComentarios() {
		Query q = entityManager.createQuery("select u from ComentarioEntity u");
		return ComentarioConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ComentarioPageDTO getComentarios(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ComentarioEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ComentarioEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ComentarioPageDTO response = new ComentarioPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ComentarioConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ComentarioDTO getComentario(Long id) {
		return ComentarioConverter.entity2PersistenceDTO(entityManager.find(ComentarioEntity.class, id));
	}

	public void deleteComentario(Long id) {
		ComentarioEntity entity=entityManager.find(ComentarioEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateComentario(ComentarioDTO detail) {
		ComentarioEntity entity=entityManager.merge(ComentarioConverter.persistenceDTO2Entity(detail));
		ComentarioConverter.entity2PersistenceDTO(entity);
	}

}