/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.pais.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.RoyalSystem.pais.logic.dto.PaisDTO;
import co.edu.uniandes.csw.RoyalSystem.pais.logic.dto.PaisPageDTO;
import co.edu.uniandes.csw.RoyalSystem.pais.logic.api._IPaisLogicService;
import co.edu.uniandes.csw.RoyalSystem.pais.persistence.api.IPaisPersistence;

public abstract class _PaisLogicService implements _IPaisLogicService {

	@Inject
	protected IPaisPersistence persistance;

	public PaisDTO createPais(PaisDTO pais){
		return persistance.createPais( pais); 
    }

	public List<PaisDTO> getPaiss(){
		return persistance.getPaiss(); 
	}

	public PaisPageDTO getPaiss(Integer page, Integer maxRecords){
		return persistance.getPaiss(page, maxRecords); 
	}

	public PaisDTO getPais(Long id){
		return persistance.getPais(id); 
	}

	public void deletePais(Long id){
	    persistance.deletePais(id); 
	}

	public void updatePais(PaisDTO pais){
	    persistance.updatePais(pais); 
	}	
}