/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.estadointercambio.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.estadointercambio.logic.dto.EstadoIntercambioDTO;
import co.edu.uniandes.csw.RoyalSystem.estadointercambio.logic.dto.EstadoIntercambioPageDTO;
import co.edu.uniandes.csw.RoyalSystem.estadointercambio.persistence.api._IEstadoIntercambioPersistence;
import co.edu.uniandes.csw.RoyalSystem.estadointercambio.persistence.converter.EstadoIntercambioConverter;
import co.edu.uniandes.csw.RoyalSystem.estadointercambio.persistence.entity.EstadoIntercambioEntity;

public abstract class _EstadoIntercambioPersistence implements _IEstadoIntercambioPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public EstadoIntercambioDTO createEstadoIntercambio(EstadoIntercambioDTO estadoIntercambio) {
		EstadoIntercambioEntity entity=EstadoIntercambioConverter.persistenceDTO2Entity(estadoIntercambio);
		entityManager.persist(entity);
		return EstadoIntercambioConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<EstadoIntercambioDTO> getEstadoIntercambios() {
		Query q = entityManager.createQuery("select u from EstadoIntercambioEntity u");
		return EstadoIntercambioConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public EstadoIntercambioPageDTO getEstadoIntercambios(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from EstadoIntercambioEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from EstadoIntercambioEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		EstadoIntercambioPageDTO response = new EstadoIntercambioPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(EstadoIntercambioConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public EstadoIntercambioDTO getEstadoIntercambio(Long id) {
		return EstadoIntercambioConverter.entity2PersistenceDTO(entityManager.find(EstadoIntercambioEntity.class, id));
	}

	public void deleteEstadoIntercambio(Long id) {
		EstadoIntercambioEntity entity=entityManager.find(EstadoIntercambioEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateEstadoIntercambio(EstadoIntercambioDTO detail) {
		EstadoIntercambioEntity entity=entityManager.merge(EstadoIntercambioConverter.persistenceDTO2Entity(detail));
		EstadoIntercambioConverter.entity2PersistenceDTO(entity);
	}

}