/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.pais.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.RoyalSystem.pais.logic.dto.PaisDTO;
import co.edu.uniandes.csw.RoyalSystem.pais.persistence.entity.PaisEntity;

public abstract class _PaisConverter {

	public static PaisDTO entity2PersistenceDTO(PaisEntity entity){
		if (entity != null) {
			PaisDTO dto = new PaisDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
			return dto;
		}else{
			return null;
		}
	}
	
	public static PaisEntity persistenceDTO2Entity(PaisDTO dto){
		if(dto!=null){
			PaisEntity entity=new PaisEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<PaisDTO> entity2PersistenceDTOList(List<PaisEntity> entities){
		List<PaisDTO> dtos=new ArrayList<PaisDTO>();
		for(PaisEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<PaisEntity> persistenceDTO2EntityList(List<PaisDTO> dtos){
		List<PaisEntity> entities=new ArrayList<PaisEntity>();
		for(PaisDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}