/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.convenio.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioPageDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.api._IConvenioPersistence;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.converter.ConvenioConverter;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.entity.ConvenioEntity;

public abstract class _ConvenioPersistence implements _IConvenioPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public ConvenioDTO createConvenio(ConvenioDTO convenio) {
		ConvenioEntity entity=ConvenioConverter.persistenceDTO2Entity(convenio);
		entityManager.persist(entity);
		return ConvenioConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ConvenioDTO> getConvenios() {
		Query q = entityManager.createQuery("select u from ConvenioEntity u");
		return ConvenioConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ConvenioPageDTO getConvenios(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ConvenioEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ConvenioEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ConvenioPageDTO response = new ConvenioPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ConvenioConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ConvenioDTO getConvenio(Long id) {
		return ConvenioConverter.entity2PersistenceDTO(entityManager.find(ConvenioEntity.class, id));
	}

	public void deleteConvenio(Long id) {
		ConvenioEntity entity=entityManager.find(ConvenioEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateConvenio(ConvenioDTO detail) {
		ConvenioEntity entity=entityManager.merge(ConvenioConverter.persistenceDTO2Entity(detail));
		ConvenioConverter.entity2PersistenceDTO(entity);
	}

}