/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.pais.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.pais.logic.dto.PaisDTO;
import co.edu.uniandes.csw.RoyalSystem.pais.logic.dto.PaisPageDTO;
import co.edu.uniandes.csw.RoyalSystem.pais.persistence.api._IPaisPersistence;
import co.edu.uniandes.csw.RoyalSystem.pais.persistence.converter.PaisConverter;
import co.edu.uniandes.csw.RoyalSystem.pais.persistence.entity.PaisEntity;

public abstract class _PaisPersistence implements _IPaisPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public PaisDTO createPais(PaisDTO pais) {
		PaisEntity entity=PaisConverter.persistenceDTO2Entity(pais);
		entityManager.persist(entity);
		return PaisConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<PaisDTO> getPaiss() {
		Query q = entityManager.createQuery("select u from PaisEntity u");
		return PaisConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public PaisPageDTO getPaiss(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from PaisEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from PaisEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		PaisPageDTO response = new PaisPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(PaisConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public PaisDTO getPais(Long id) {
		return PaisConverter.entity2PersistenceDTO(entityManager.find(PaisEntity.class, id));
	}

	public void deletePais(Long id) {
		PaisEntity entity=entityManager.find(PaisEntity.class, id);
		entityManager.remove(entity);
	}

	public void updatePais(PaisDTO detail) {
		PaisEntity entity=entityManager.merge(PaisConverter.persistenceDTO2Entity(detail));
		PaisConverter.entity2PersistenceDTO(entity);
	}

}