/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.archivo.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.archivo.logic.dto.ArchivoDTO;
import co.edu.uniandes.csw.RoyalSystem.archivo.logic.dto.ArchivoPageDTO;
import co.edu.uniandes.csw.RoyalSystem.archivo.persistence.api._IArchivoPersistence;
import co.edu.uniandes.csw.RoyalSystem.archivo.persistence.converter.ArchivoConverter;
import co.edu.uniandes.csw.RoyalSystem.archivo.persistence.entity.ArchivoEntity;

public abstract class _ArchivoPersistence implements _IArchivoPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public ArchivoDTO createArchivo(ArchivoDTO archivo) {
		ArchivoEntity entity=ArchivoConverter.persistenceDTO2Entity(archivo);
		entityManager.persist(entity);
		return ArchivoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ArchivoDTO> getArchivos() {
		Query q = entityManager.createQuery("select u from ArchivoEntity u");
		return ArchivoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ArchivoPageDTO getArchivos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ArchivoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ArchivoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ArchivoPageDTO response = new ArchivoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ArchivoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ArchivoDTO getArchivo(Long id) {
		return ArchivoConverter.entity2PersistenceDTO(entityManager.find(ArchivoEntity.class, id));
	}

	public void deleteArchivo(Long id) {
		ArchivoEntity entity=entityManager.find(ArchivoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateArchivo(ArchivoDTO detail) {
		ArchivoEntity entity=entityManager.merge(ArchivoConverter.persistenceDTO2Entity(detail));
		ArchivoConverter.entity2PersistenceDTO(entity);
	}

}