/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.experiencia.master.persistence;
import co.edu.uniandes.csw.RoyalSystem.archivo.logic.dto.ArchivoDTO;
import co.edu.uniandes.csw.RoyalSystem.experiencia.master.persistence.entity.ExperienciaarchivoEntity;
import co.edu.uniandes.csw.RoyalSystem.archivo.persistence.converter.ArchivoConverter;
import co.edu.uniandes.csw.RoyalSystem.comentario.logic.dto.ComentarioDTO;
import co.edu.uniandes.csw.RoyalSystem.experiencia.master.persistence.entity.ExperienciacomentarioEntity;
import co.edu.uniandes.csw.RoyalSystem.comentario.persistence.converter.ComentarioConverter;
import co.edu.uniandes.csw.RoyalSystem.experiencia.logic.dto.ExperienciaDTO;
import co.edu.uniandes.csw.RoyalSystem.experiencia.master.logic.dto.ExperienciaMasterDTO;
import co.edu.uniandes.csw.RoyalSystem.experiencia.master.persistence.api._IExperienciaMasterPersistence;
import co.edu.uniandes.csw.RoyalSystem.experiencia.persistence.api.IExperienciaPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _ExperienciaMasterPersistence implements _IExperienciaMasterPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IExperienciaPersistence experienciaPersistence;  

    public ExperienciaMasterDTO getExperiencia(Long experienciaId) {
        ExperienciaMasterDTO experienciaMasterDTO = new ExperienciaMasterDTO();
        ExperienciaDTO experiencia = experienciaPersistence.getExperiencia(experienciaId);
        experienciaMasterDTO.setExperienciaEntity(experiencia);
        experienciaMasterDTO.setListarchivo(getExperienciaarchivoEntityList(experienciaId));
        experienciaMasterDTO.setListcomentario(getExperienciacomentarioEntityList(experienciaId));
        return experienciaMasterDTO;
    }

    public ExperienciaarchivoEntity createExperienciaarchivoEntity(ExperienciaarchivoEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteExperienciaarchivoEntity(Long experienciaId, Long archivoId) {
        Query q = entityManager.createNamedQuery("ExperienciaarchivoEntity.deleteExperienciaarchivoEntity");
        q.setParameter("experienciaId", experienciaId);
        q.setParameter("archivoId", archivoId);
        q.executeUpdate();
    }

    public List<ArchivoDTO> getExperienciaarchivoEntityList(Long experienciaId) {
        ArrayList<ArchivoDTO> resp = new ArrayList<ArchivoDTO>();
        Query q = entityManager.createNamedQuery("ExperienciaarchivoEntity.getByMasterId");
        q.setParameter("experienciaId",experienciaId);
        List<ExperienciaarchivoEntity> qResult =  q.getResultList();
        for (ExperienciaarchivoEntity entity : qResult) { 
            if(entity.getArchivoIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ArchivoConverter.entity2PersistenceDTO(entity.getArchivoIdEntity()));
        }
        return resp;
    }
    public ExperienciacomentarioEntity createExperienciacomentarioEntity(ExperienciacomentarioEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteExperienciacomentarioEntity(Long experienciaId, Long comentarioId) {
        Query q = entityManager.createNamedQuery("ExperienciacomentarioEntity.deleteExperienciacomentarioEntity");
        q.setParameter("experienciaId", experienciaId);
        q.setParameter("comentarioId", comentarioId);
        q.executeUpdate();
    }

    public List<ComentarioDTO> getExperienciacomentarioEntityList(Long experienciaId) {
        ArrayList<ComentarioDTO> resp = new ArrayList<ComentarioDTO>();
        Query q = entityManager.createNamedQuery("ExperienciacomentarioEntity.getByMasterId");
        q.setParameter("experienciaId",experienciaId);
        List<ExperienciacomentarioEntity> qResult =  q.getResultList();
        for (ExperienciacomentarioEntity entity : qResult) { 
            if(entity.getComentarioIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ComentarioConverter.entity2PersistenceDTO(entity.getComentarioIdEntity()));
        }
        return resp;
    }

}
