/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.experiencia.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.RoyalSystem.experiencia.logic.dto.ExperienciaDTO;
import co.edu.uniandes.csw.RoyalSystem.experiencia.persistence.entity.ExperienciaEntity;

public abstract class _ExperienciaConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static ExperienciaDTO entity2PersistenceDTO(ExperienciaEntity entity){
		if (entity != null) {
			ExperienciaDTO dto = new ExperienciaDTO();
					dto.setTexto(entity.getTexto());
					dto.setName(entity.getName());
					dto.setId(entity.getId());
					dto.setTitulo(entity.getTitulo());
 
			    if(entity.getFecha() != null){
					dto.setFecha(DATE_FORMAT.format(entity.getFecha()));
				}	
			return dto;
		}else{
			return null;
		}
	}
	
	public static ExperienciaEntity persistenceDTO2Entity(ExperienciaDTO dto){
		if(dto!=null){
			ExperienciaEntity entity=new ExperienciaEntity();
					entity.setTexto(dto.getTexto());
			
					entity.setName(dto.getName());
			
					entity.setId(dto.getId());
			
					entity.setTitulo(dto.getTitulo());
			
 
			      try{ 
			        if(dto.getFecha() != null){
						entity.setFecha(DATE_FORMAT.parse(dto.getFecha()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_ExperienciaConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ExperienciaDTO> entity2PersistenceDTOList(List<ExperienciaEntity> entities){
		List<ExperienciaDTO> dtos=new ArrayList<ExperienciaDTO>();
		for(ExperienciaEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ExperienciaEntity> persistenceDTO2EntityList(List<ExperienciaDTO> dtos){
		List<ExperienciaEntity> entities=new ArrayList<ExperienciaEntity>();
		for(ExperienciaDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}