/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraPageDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.api._IEntidadExtranjeraPersistence;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.converter.EntidadExtranjeraConverter;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.entity.EntidadExtranjeraEntity;

public abstract class _EntidadExtranjeraPersistence implements _IEntidadExtranjeraPersistence {

  	@PersistenceContext(unitName="internacionalizacionPU")
 
	protected EntityManager entityManager;
	
	public EntidadExtranjeraDTO createEntidadExtranjera(EntidadExtranjeraDTO entidadExtranjera) {
		EntidadExtranjeraEntity entity=EntidadExtranjeraConverter.persistenceDTO2Entity(entidadExtranjera);
		entityManager.persist(entity);
		return EntidadExtranjeraConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<EntidadExtranjeraDTO> getEntidadExtranjeras() {
		Query q = entityManager.createQuery("select u from EntidadExtranjeraEntity u");
		return EntidadExtranjeraConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public EntidadExtranjeraPageDTO getEntidadExtranjeras(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from EntidadExtranjeraEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from EntidadExtranjeraEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		EntidadExtranjeraPageDTO response = new EntidadExtranjeraPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(EntidadExtranjeraConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public EntidadExtranjeraDTO getEntidadExtranjera(Long id) {
		return EntidadExtranjeraConverter.entity2PersistenceDTO(entityManager.find(EntidadExtranjeraEntity.class, id));
	}

	public void deleteEntidadExtranjera(Long id) {
		EntidadExtranjeraEntity entity=entityManager.find(EntidadExtranjeraEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateEntidadExtranjera(EntidadExtranjeraDTO detail) {
		EntidadExtranjeraEntity entity=entityManager.merge(EntidadExtranjeraConverter.persistenceDTO2Entity(detail));
		EntidadExtranjeraConverter.entity2PersistenceDTO(entity);
	}

}