/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.estadohomologacion.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.logic.dto.EstadoHomologacionPageDTO;
import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.logic.dto.EstadoHomologacionDTO;
import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.persistence.api.IEstadoHomologacionPersistence;
import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.persistence.entity.EstadoHomologacionEntity;
import co.edu.uniandes.csw.RoyalSystem.estadohomologacion.persistence.converter.EstadoHomologacionConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EstadoHomologacionPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EstadoHomologacionPersistence.class.getPackage())
				.addPackage(EstadoHomologacionEntity.class.getPackage())
				.addPackage(IEstadoHomologacionPersistence.class.getPackage())
                .addPackage(EstadoHomologacionDTO.class.getPackage())
                .addPackage(EstadoHomologacionConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEstadoHomologacionPersistence estadoHomologacionPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EstadoHomologacionEntity").executeUpdate();
	}

	private List<EstadoHomologacionEntity> data=new ArrayList<EstadoHomologacionEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EstadoHomologacionEntity entity=new EstadoHomologacionEntity();
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEstadoHomologacionTest(){
		EstadoHomologacionDTO dto=new EstadoHomologacionDTO();
		dto.setName(generateRandom(String.class));
		
		EstadoHomologacionDTO result=estadoHomologacionPersistence.createEstadoHomologacion(dto);
		
		Assert.assertNotNull(result);
		
		EstadoHomologacionEntity entity=em.find(EstadoHomologacionEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getEstadoHomologacionsTest(){
		List<EstadoHomologacionDTO> list=estadoHomologacionPersistence.getEstadoHomologacions();
		Assert.assertEquals(list.size(), data.size());
        for(EstadoHomologacionDTO dto:list){
        	boolean found=false;
            for(EstadoHomologacionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEstadoHomologacionTest(){
		EstadoHomologacionEntity entity=data.get(0);
		EstadoHomologacionDTO dto=estadoHomologacionPersistence.getEstadoHomologacion(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteEstadoHomologacionTest(){
		EstadoHomologacionEntity entity=data.get(0);
		estadoHomologacionPersistence.deleteEstadoHomologacion(entity.getId());
        EstadoHomologacionEntity deleted=em.find(EstadoHomologacionEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEstadoHomologacionTest(){
		EstadoHomologacionEntity entity=data.get(0);
		
		EstadoHomologacionDTO dto=new EstadoHomologacionDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		
		
		estadoHomologacionPersistence.updateEstadoHomologacion(dto);
		
		
		EstadoHomologacionEntity resp=em.find(EstadoHomologacionEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
	
	@Test
	public void getEstadoHomologacionPaginationTest(){
		//Page 1
		EstadoHomologacionPageDTO dto1=estadoHomologacionPersistence.getEstadoHomologacions(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        EstadoHomologacionPageDTO dto2=estadoHomologacionPersistence.getEstadoHomologacions(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(EstadoHomologacionDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(EstadoHomologacionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EstadoHomologacionDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EstadoHomologacionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}