/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.convenio.master.persistence.entity;

import co.edu.uniandes.csw.RoyalSystem.homologacion.persistence.entity.HomologacionEntity;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.entity.ConvenioEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ConveniohomologacionEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ConveniohomologacionEntity.getByMasterId", query = "SELECT  u FROM ConveniohomologacionEntity u WHERE u.convenioId=:convenioId"),
    @NamedQuery(name = "ConveniohomologacionEntity.deleteConveniohomologacionEntity", query = "DELETE FROM ConveniohomologacionEntity u WHERE u.convenioId=:convenioId and  u.homologacionId=:homologacionId")
})
public class ConveniohomologacionEntity implements Serializable {

    @Id
    @Column(name = "convenioId")
    private Long convenioId;
    @Id
    @Column(name = "homologacionId")
    private Long homologacionId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "convenioId", referencedColumnName = "id")
    @JoinFetch
    private HomologacionEntity convenioIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "homologacionId", referencedColumnName = "id")
    @JoinFetch
    private HomologacionEntity homologacionIdEntity; 

    public ConveniohomologacionEntity() {
    }

    public ConveniohomologacionEntity(Long convenioId, Long homologacionId) {
        this.convenioId =convenioId;
        this.homologacionId = homologacionId;
    }

    public Long getConvenioId() {
        return convenioId;
    }

    public void setConvenioId(Long convenioId) {
        this.convenioId = convenioId;
    }

    public Long getHomologacionId() {
        return homologacionId;
    }

    public void setHomologacionId(Long homologacionId) {
        this.homologacionId = homologacionId;
    }

    public HomologacionEntity getConvenioIdEntity() {
        return convenioIdEntity;
    }

    public void setConvenioIdEntity(HomologacionEntity convenioIdEntity) {
        this.convenioIdEntity = convenioIdEntity;
    }

    public HomologacionEntity getHomologacionIdEntity() {
        return homologacionIdEntity;
    }

    public void setHomologacionIdEntity(HomologacionEntity homologacionIdEntity) {
        this.homologacionIdEntity = homologacionIdEntity;
    }

}
