/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.homologacion.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.dto.HomologacionPageDTO;
import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.dto.HomologacionDTO;
import co.edu.uniandes.csw.RoyalSystem.homologacion.persistence.api.IHomologacionPersistence;
import co.edu.uniandes.csw.RoyalSystem.homologacion.persistence.entity.HomologacionEntity;
import co.edu.uniandes.csw.RoyalSystem.homologacion.persistence.converter.HomologacionConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class HomologacionPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(HomologacionPersistence.class.getPackage())
				.addPackage(HomologacionEntity.class.getPackage())
				.addPackage(IHomologacionPersistence.class.getPackage())
                .addPackage(HomologacionDTO.class.getPackage())
                .addPackage(HomologacionConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IHomologacionPersistence homologacionPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from HomologacionEntity").executeUpdate();
	}

	private List<HomologacionEntity> data=new ArrayList<HomologacionEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			HomologacionEntity entity=new HomologacionEntity();
			entity.setName(generateRandom(String.class));
			entity.setMateriaExtranjera(generateRandom(String.class));
			entity.setEquivalenciaCreditos(generateRandom(Integer.class));
			entity.setEstadoId(generateRandom(Long.class));
			entity.setMateriauniandesId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createHomologacionTest(){
		HomologacionDTO dto=new HomologacionDTO();
		dto.setName(generateRandom(String.class));
		dto.setMateriaExtranjera(generateRandom(String.class));
		dto.setEquivalenciaCreditos(generateRandom(Integer.class));
		dto.setEstadoId(generateRandom(Long.class));
		dto.setMateriauniandesId(generateRandom(Long.class));
		
		HomologacionDTO result=homologacionPersistence.createHomologacion(dto);
		
		Assert.assertNotNull(result);
		
		HomologacionEntity entity=em.find(HomologacionEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getMateriaExtranjera(), entity.getMateriaExtranjera());
		Assert.assertEquals(dto.getEquivalenciaCreditos(), entity.getEquivalenciaCreditos());
		Assert.assertEquals(dto.getEstadoId(), entity.getEstadoId());
		Assert.assertEquals(dto.getMateriauniandesId(), entity.getMateriauniandesId());
	}
	
	@Test
	public void getHomologacionsTest(){
		List<HomologacionDTO> list=homologacionPersistence.getHomologacions();
		Assert.assertEquals(list.size(), data.size());
        for(HomologacionDTO dto:list){
        	boolean found=false;
            for(HomologacionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getHomologacionTest(){
		HomologacionEntity entity=data.get(0);
		HomologacionDTO dto=homologacionPersistence.getHomologacion(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getMateriaExtranjera(), dto.getMateriaExtranjera());
		Assert.assertEquals(entity.getEquivalenciaCreditos(), dto.getEquivalenciaCreditos());
		Assert.assertEquals(entity.getEstadoId(), dto.getEstadoId());
		Assert.assertEquals(entity.getMateriauniandesId(), dto.getMateriauniandesId());
        
	}
	
	@Test
	public void deleteHomologacionTest(){
		HomologacionEntity entity=data.get(0);
		homologacionPersistence.deleteHomologacion(entity.getId());
        HomologacionEntity deleted=em.find(HomologacionEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateHomologacionTest(){
		HomologacionEntity entity=data.get(0);
		
		HomologacionDTO dto=new HomologacionDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setMateriaExtranjera(generateRandom(String.class));
		dto.setEquivalenciaCreditos(generateRandom(Integer.class));
		dto.setEstadoId(generateRandom(Long.class));
		dto.setMateriauniandesId(generateRandom(Long.class));
		
		
		homologacionPersistence.updateHomologacion(dto);
		
		
		HomologacionEntity resp=em.find(HomologacionEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getMateriaExtranjera(), resp.getMateriaExtranjera());	
		Assert.assertEquals(dto.getEquivalenciaCreditos(), resp.getEquivalenciaCreditos());	
		Assert.assertEquals(dto.getEstadoId(), resp.getEstadoId());	
		Assert.assertEquals(dto.getMateriauniandesId(), resp.getMateriauniandesId());	
	}
	
	@Test
	public void getHomologacionPaginationTest(){
		//Page 1
		HomologacionPageDTO dto1=homologacionPersistence.getHomologacions(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        HomologacionPageDTO dto2=homologacionPersistence.getHomologacions(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(HomologacionDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(HomologacionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(HomologacionDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(HomologacionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}