/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraPageDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.logic.dto.EntidadExtranjeraDTO;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.api.IEntidadExtranjeraPersistence;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.entity.EntidadExtranjeraEntity;
import co.edu.uniandes.csw.RoyalSystem.entidadextranjera.persistence.converter.EntidadExtranjeraConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EntidadExtranjeraPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EntidadExtranjeraPersistence.class.getPackage())
				.addPackage(EntidadExtranjeraEntity.class.getPackage())
				.addPackage(IEntidadExtranjeraPersistence.class.getPackage())
                .addPackage(EntidadExtranjeraDTO.class.getPackage())
                .addPackage(EntidadExtranjeraConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEntidadExtranjeraPersistence entidadExtranjeraPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EntidadExtranjeraEntity").executeUpdate();
	}

	private List<EntidadExtranjeraEntity> data=new ArrayList<EntidadExtranjeraEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EntidadExtranjeraEntity entity=new EntidadExtranjeraEntity();
			entity.setName(generateRandom(String.class));
			entity.setLink(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEntidadExtranjeraTest(){
		EntidadExtranjeraDTO dto=new EntidadExtranjeraDTO();
		dto.setName(generateRandom(String.class));
		dto.setLink(generateRandom(String.class));
		
		EntidadExtranjeraDTO result=entidadExtranjeraPersistence.createEntidadExtranjera(dto);
		
		Assert.assertNotNull(result);
		
		EntidadExtranjeraEntity entity=em.find(EntidadExtranjeraEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getLink(), entity.getLink());
	}
	
	@Test
	public void getEntidadExtranjerasTest(){
		List<EntidadExtranjeraDTO> list=entidadExtranjeraPersistence.getEntidadExtranjeras();
		Assert.assertEquals(list.size(), data.size());
        for(EntidadExtranjeraDTO dto:list){
        	boolean found=false;
            for(EntidadExtranjeraEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEntidadExtranjeraTest(){
		EntidadExtranjeraEntity entity=data.get(0);
		EntidadExtranjeraDTO dto=entidadExtranjeraPersistence.getEntidadExtranjera(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getLink(), dto.getLink());
        
	}
	
	@Test
	public void deleteEntidadExtranjeraTest(){
		EntidadExtranjeraEntity entity=data.get(0);
		entidadExtranjeraPersistence.deleteEntidadExtranjera(entity.getId());
        EntidadExtranjeraEntity deleted=em.find(EntidadExtranjeraEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEntidadExtranjeraTest(){
		EntidadExtranjeraEntity entity=data.get(0);
		
		EntidadExtranjeraDTO dto=new EntidadExtranjeraDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setLink(generateRandom(String.class));
		
		
		entidadExtranjeraPersistence.updateEntidadExtranjera(dto);
		
		
		EntidadExtranjeraEntity resp=em.find(EntidadExtranjeraEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getLink(), resp.getLink());	
	}
	
	@Test
	public void getEntidadExtranjeraPaginationTest(){
		//Page 1
		EntidadExtranjeraPageDTO dto1=entidadExtranjeraPersistence.getEntidadExtranjeras(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        EntidadExtranjeraPageDTO dto2=entidadExtranjeraPersistence.getEntidadExtranjeras(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(EntidadExtranjeraDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(EntidadExtranjeraEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EntidadExtranjeraDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EntidadExtranjeraEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}