/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.materiauniandes.service;

import java.util.List;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.inject.Inject;

import co.edu.uniandes.csw.RoyalSystem.materiauniandes.logic.api.IMateriaUniandesLogicService;
import co.edu.uniandes.csw.RoyalSystem.materiauniandes.logic.dto.MateriaUniandesDTO;
import co.edu.uniandes.csw.RoyalSystem.materiauniandes.logic.dto.MateriaUniandesPageDTO;


public abstract class _MateriaUniandesService {

	@Inject
	protected IMateriaUniandesLogicService materiaUniandesLogicService;
	
	@POST
	public MateriaUniandesDTO createMateriaUniandes(MateriaUniandesDTO materiaUniandes){
		return materiaUniandesLogicService.createMateriaUniandes(materiaUniandes);
	}
	
	@DELETE
	@Path("{id}")
	public void deleteMateriaUniandes(@PathParam("id") Long id){
		materiaUniandesLogicService.deleteMateriaUniandes(id);
	}
	
	@GET
	public MateriaUniandesPageDTO getMateriaUniandess(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
		return materiaUniandesLogicService.getMateriaUniandess(page, maxRecords);
	}
	
	@GET
	@Path("{id}")
	public MateriaUniandesDTO getMateriaUniandes(@PathParam("id") Long id){
		return materiaUniandesLogicService.getMateriaUniandes(id);
	}
	
	@PUT
	public void updateMateriaUniandes(@PathParam("id") Long id, MateriaUniandesDTO materiaUniandes){
		materiaUniandesLogicService.updateMateriaUniandes(materiaUniandes);
	}
	
}