/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.homologacion.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.dto.HomologacionDTO;
import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.dto.HomologacionPageDTO;
import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.api._IHomologacionLogicService;

public abstract class _HomologacionMockLogicService implements _IHomologacionLogicService {

	private Long id= new Long(1);
	protected List<HomologacionDTO> data=new ArrayList<HomologacionDTO>();

	public HomologacionDTO createHomologacion(HomologacionDTO homologacion){
		id++;
		homologacion.setId(id);
		data.add(homologacion);
		return homologacion;
    }
    
    public List<HomologacionDTO> getHomologacions(){
		return data; 
	}

	public HomologacionPageDTO getHomologacions(Integer page, Integer maxRecords){
		HomologacionPageDTO response = new HomologacionPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public HomologacionDTO getHomologacion(Long id){
		for(HomologacionDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteHomologacion(Long id){
	    HomologacionDTO delete=null;
		for(HomologacionDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateHomologacion(HomologacionDTO homologacion){
	    HomologacionDTO delete=null;
		for(HomologacionDTO data1:data){
			if(data1.getId().equals(homologacion.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(homologacion);
		} 
	}	
}