/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.intercambio.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.RoyalSystem.intercambio.logic.dto.IntercambioPageDTO;
import co.edu.uniandes.csw.RoyalSystem.intercambio.logic.dto.IntercambioDTO;
import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.api.IIntercambioPersistence;
import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.entity.IntercambioEntity;
import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.converter.IntercambioConverter;
import static co.edu.uniandes.csw.RoyalSystem.util._TestUtil.*;

@RunWith(Arquillian.class)
public class IntercambioPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(IntercambioPersistence.class.getPackage())
				.addPackage(IntercambioEntity.class.getPackage())
				.addPackage(IIntercambioPersistence.class.getPackage())
                .addPackage(IntercambioDTO.class.getPackage())
                .addPackage(IntercambioConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IIntercambioPersistence intercambioPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from IntercambioEntity").executeUpdate();
	}

	private List<IntercambioEntity> data=new ArrayList<IntercambioEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			IntercambioEntity entity=new IntercambioEntity();
			entity.setName(generateRandom(String.class));
			entity.setFechaCreacion(generateRandom(Date.class));
			entity.setEstudianteId(generateRandom(Long.class));
			entity.setEstadoId(generateRandom(Long.class));
			entity.setExperienciaId(generateRandom(Long.class));
			entity.setConvenioId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createIntercambioTest(){
		IntercambioDTO dto=new IntercambioDTO();
		dto.setName(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setEstudianteId(generateRandom(Long.class));
		dto.setEstadoId(generateRandom(Long.class));
		dto.setExperienciaId(generateRandom(Long.class));
		dto.setConvenioId(generateRandom(Long.class));
		
		IntercambioDTO result=intercambioPersistence.createIntercambio(dto);
		
		Assert.assertNotNull(result);
		
		IntercambioEntity entity=em.find(IntercambioEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
Assert.assertEquals(parseDate(dto.getFechaCreacion()), entity.getFechaCreacion());	
		Assert.assertEquals(dto.getEstudianteId(), entity.getEstudianteId());
		Assert.assertEquals(dto.getEstadoId(), entity.getEstadoId());
		Assert.assertEquals(dto.getExperienciaId(), entity.getExperienciaId());
		Assert.assertEquals(dto.getConvenioId(), entity.getConvenioId());
	}
	
	@Test
	public void getIntercambiosTest(){
		List<IntercambioDTO> list=intercambioPersistence.getIntercambios();
		Assert.assertEquals(list.size(), data.size());
        for(IntercambioDTO dto:list){
        	boolean found=false;
            for(IntercambioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getIntercambioTest(){
		IntercambioEntity entity=data.get(0);
		IntercambioDTO dto=intercambioPersistence.getIntercambio(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getEstudianteId(), dto.getEstudianteId());
		Assert.assertEquals(entity.getEstadoId(), dto.getEstadoId());
		Assert.assertEquals(entity.getExperienciaId(), dto.getExperienciaId());
		Assert.assertEquals(entity.getConvenioId(), dto.getConvenioId());
        
	}
	
	@Test
	public void deleteIntercambioTest(){
		IntercambioEntity entity=data.get(0);
		intercambioPersistence.deleteIntercambio(entity.getId());
        IntercambioEntity deleted=em.find(IntercambioEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateIntercambioTest(){
		IntercambioEntity entity=data.get(0);
		
		IntercambioDTO dto=new IntercambioDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
dto.setFechaCreacion(generateRandomDate());
		dto.setEstudianteId(generateRandom(Long.class));
		dto.setEstadoId(generateRandom(Long.class));
		dto.setExperienciaId(generateRandom(Long.class));
		dto.setConvenioId(generateRandom(Long.class));
		
		
		intercambioPersistence.updateIntercambio(dto);
		
		
		IntercambioEntity resp=em.find(IntercambioEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
Assert.assertEquals(parseDate(dto.getFechaCreacion()), resp.getFechaCreacion());
		Assert.assertEquals(dto.getEstudianteId(), resp.getEstudianteId());	
		Assert.assertEquals(dto.getEstadoId(), resp.getEstadoId());	
		Assert.assertEquals(dto.getExperienciaId(), resp.getExperienciaId());	
		Assert.assertEquals(dto.getConvenioId(), resp.getConvenioId());	
	}
	
	@Test
	public void getIntercambioPaginationTest(){
		//Page 1
		IntercambioPageDTO dto1=intercambioPersistence.getIntercambios(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        IntercambioPageDTO dto2=intercambioPersistence.getIntercambios(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(IntercambioDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(IntercambioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(IntercambioDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(IntercambioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}