/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.RoyalSystem.homologacion.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.dto.HomologacionDTO;
import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.dto.HomologacionPageDTO;
import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.api._IHomologacionLogicService;
import co.edu.uniandes.csw.RoyalSystem.homologacion.persistence.api.IHomologacionPersistence;

public abstract class _HomologacionLogicService implements _IHomologacionLogicService {

	@Inject
	protected IHomologacionPersistence persistance;

	public HomologacionDTO createHomologacion(HomologacionDTO homologacion){
		return persistance.createHomologacion( homologacion); 
    }

	public List<HomologacionDTO> getHomologacions(){
		return persistance.getHomologacions(); 
	}

	public HomologacionPageDTO getHomologacions(Integer page, Integer maxRecords){
		return persistance.getHomologacions(page, maxRecords); 
	}

	public HomologacionDTO getHomologacion(Long id){
		return persistance.getHomologacion(id); 
	}

	public void deleteHomologacion(Long id){
	    persistance.deleteHomologacion(id); 
	}

	public void updateHomologacion(HomologacionDTO homologacion){
	    persistance.updateHomologacion(homologacion); 
	}	
}